### ISSUE TITLE
User can view details of a single random TV show or movie

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view details of a single random TV show or Movie

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

 An application for Movie / TV Show fans who cannot decide what to watch due to the overwhelming selections available 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 11 56 55 AM](https://user-images.githubusercontent.com/99229316/163860449-a7d99493-fcf2-4944-8dfd-dca860167245.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create necessary HTML, CSS, and JavaScript files
- [x] Link all files together
- [x] Style the HTML and CSS to match the Wireframe
- [x] integrate the MostPopularMovies API and MostPopularTVShow API to get movie data
- [x] add the necessary buttons to popup for movie entry
- [x] add event listeners to buttons
- [x] add functionality to popup so user can close popup
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
