### ISSUE TITLE
User can add a TV show or movie to watchlist

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a TV show or movie to watchlist

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

 An application for Movie / TV Show fans who cannot decide what to watch due to the overwhelming selections available 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 12 00 34 PM](https://user-images.githubusercontent.com/99229316/163860905-c08b74e9-9941-474d-a24a-b147256c7fdd.png)
![Screen Shot 2022-04-18 at 12 00 48 PM](https://user-images.githubusercontent.com/99229316/163860915-8f849ba5-8035-4b50-ba05-57338168e2a8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add add icon to each entry 
- [x] add entry to watchlist 
- [x] incorporate data.js with local storage
- [x] make sure the entries are added to data.js
- [x] test functionality in private browser 
- [x] create modal confirming entry has been added to watch list
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop
