### ISSUE TITLE
Users can view their watchlist.

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

An application for Movie / TV Show fans who cannot decide what to watch due to the overwhelming selections available

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 12 02 33 PM](https://user-images.githubusercontent.com/99229316/163861164-6dbfe169-79f8-410e-b076-c5ac9c4578ca.png)
![Screen Shot 2022-04-18 at 12 02 24 PM](https://user-images.githubusercontent.com/99229316/163861169-92d066d0-eea2-4809-8638-2c3779983bf1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add archive button to nav bar
- [x] add EventListener to archive button that will bring user to their watchlist
- [x] if watchlist is empty, display message to user that watchlist is empty
- [x] create DOMtree that will create watchlist entry every time an entry is added to watchlist
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
