### ISSUE TITLE
Users can view a list of top movies in theaters now.

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of top movies in theaters now.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

An application for Movie / TV Show fans who cannot decide what to watch due to the overwhelming selections available 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 12 25 59 PM](https://user-images.githubusercontent.com/99229316/163864717-8488dde1-252f-43f2-a45e-64842281fd2b.png)
![Screen Shot 2022-04-18 at 12 26 10 PM](https://user-images.githubusercontent.com/99229316/163864722-e9c516d9-6e4d-47a7-bfa5-406c9e88098e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create 'In Theaters' button for homepage
- [x] add functionality to In Theaters button
- [x] once in theaters button is clicked, display new container that displays current movies in theaters
- [x] be able to view more information on movies by clicking on the posters
- [x] be able to add 'in theaters' movie to watchlist
- [x] be able to view movies through watchlist 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
