### ISSUE TITLE
Users can delete their watchlist entries.

### ISSUE THREAD

**Issue by dylandevei** [dylandevei/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can delete their watchlist entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

An application for Movie / TV Show fans who cannot decide what to watch due to the overwhelming selections available
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-18 at 12 27 15 PM](https://user-images.githubusercontent.com/99229316/163864900-b32c06b8-c254-4b4a-a9c0-510c601385f3.png)
![Screen Shot 2022-04-18 at 12 27 25 PM](https://user-images.githubusercontent.com/99229316/163864904-727d4563-ed07-4277-af65-c936ebd7947d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create trash icon for entries
- [x] add functionality to the trash icon that will bring up modal
- [x] create modal with overlay
- [x] display a confirmation message for entry delete
- [x] delete entry from watchlist
- [x] delete entry from data model 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
